// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using projeto.Data;

#nullable disable

namespace AMoVeRLogistica.Migrations
{
    [DbContext(typeof(AMoverContext))]
    [Migration("20260620130047_LocationNodeTaskOrder")]
    partial class LocationNodeTaskOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlertUser", b =>
                {
                    b.Property<int>("targetedAlertsID")
                        .HasColumnType("integer");

                    b.Property<int>("targetsID")
                        .HasColumnType("integer");

                    b.HasKey("targetedAlertsID", "targetsID");

                    b.HasIndex("targetsID");

                    b.ToTable("AlertUser");
                });

            modelBuilder.Entity("projeto.Data.Models.Alert", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("adminID")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("adminID");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("projeto.Data.Models.ApiKey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("apiKeys");
                });

            modelBuilder.Entity("projeto.Data.Models.AssistanceMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AssistanceRequestID")
                        .HasColumnType("integer");

                    b.Property<string>("sender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("AssistanceRequestID");

                    b.ToTable("assistanceMessages");
                });

            modelBuilder.Entity("projeto.Data.Models.AssistanceRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("TargetUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("TargetUserID");

                    b.ToTable("assistanceRequests");
                });

            modelBuilder.Entity("projeto.Data.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("projeto.Data.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("projeto.Data.Models.LocationNode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("availableTimeEnds")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("availableTimeStart")
                        .HasColumnType("interval");

                    b.Property<float>("latitude")
                        .HasColumnType("real");

                    b.Property<float>("longintude")
                        .HasColumnType("real");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("LocationNode");
                });

            modelBuilder.Entity("projeto.Data.Models.LocationNodeTask", b =>
                {
                    b.Property<int>("NodeID")
                        .HasColumnType("integer");

                    b.Property<int>("TaskID")
                        .HasColumnType("integer");

                    b.Property<int>("stopOrder")
                        .HasColumnType("integer");

                    b.HasKey("NodeID", "TaskID");

                    b.HasIndex("TaskID");

                    b.ToTable("LocationNodeTask");
                });

            modelBuilder.Entity("projeto.Data.Models.Maintenance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("motorcycleid")
                        .HasColumnType("integer");

                    b.Property<bool>("resolved")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("motorcycleid");

                    b.ToTable("maintenances");
                });

            modelBuilder.Entity("projeto.Data.Models.MessageLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleVID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("messageLogs");
                });

            modelBuilder.Entity("projeto.Data.Models.Plan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("isOptimized")
                        .HasColumnType("boolean");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("userID");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("projeto.Data.Models.Service", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("companyID")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("companyID");

                    b.ToTable("services");
                });

            modelBuilder.Entity("projeto.Data.Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<TimeSpan?>("availableTimeEnds")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("availableTimeStart")
                        .HasColumnType("interval");

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<int>("clientID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("door_number")
                        .HasColumnType("text");

                    b.Property<string>("floor")
                        .HasColumnType("text");

                    b.Property<string>("instructions")
                        .HasColumnType("text");

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.Property<int?>("planID")
                        .HasColumnType("integer");

                    b.Property<string>("postal_code")
                        .HasColumnType("text");

                    b.Property<string>("priority")
                        .HasColumnType("text");

                    b.Property<string>("recurrence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("serviceID")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("street")
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("userID")
                        .HasColumnType("integer");

                    b.Property<int?>("vehicleID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("clientID");

                    b.HasIndex("planID");

                    b.HasIndex("serviceID");

                    b.HasIndex("userID");

                    b.HasIndex("vehicleID");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("projeto.Data.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("citizenCard")
                        .HasColumnType("text");

                    b.Property<int?>("companyID")
                        .HasColumnType("integer");

                    b.Property<string>("driverLicense")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<string>("photoUrl")
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("companyID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("projeto.Data.Models.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("VID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("batteryCapacity")
                        .HasColumnType("real");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("cargoCapacity")
                        .HasColumnType("real");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ownerID")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ownerID");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("AlertUser", b =>
                {
                    b.HasOne("projeto.Data.Models.Alert", null)
                        .WithMany()
                        .HasForeignKey("targetedAlertsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projeto.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("targetsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("projeto.Data.Models.Alert", b =>
                {
                    b.HasOne("projeto.Data.Models.User", "admin")
                        .WithMany("managedAlerts")
                        .HasForeignKey("adminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");
                });

            modelBuilder.Entity("projeto.Data.Models.AssistanceMessage", b =>
                {
                    b.HasOne("projeto.Data.Models.AssistanceRequest", "AssistanceRequest")
                        .WithMany("Messages")
                        .HasForeignKey("AssistanceRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssistanceRequest");
                });

            modelBuilder.Entity("projeto.Data.Models.AssistanceRequest", b =>
                {
                    b.HasOne("projeto.Data.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserID");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("projeto.Data.Models.LocationNodeTask", b =>
                {
                    b.HasOne("projeto.Data.Models.LocationNode", "LocationNode")
                        .WithMany("LocationNodeTasks")
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projeto.Data.Models.Task", "Task")
                        .WithMany("LocationNodeTasks")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationNode");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("projeto.Data.Models.Maintenance", b =>
                {
                    b.HasOne("projeto.Data.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("motorcycleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("projeto.Data.Models.Plan", b =>
                {
                    b.HasOne("projeto.Data.Models.User", "user")
                        .WithMany("plans")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("projeto.Data.Models.Service", b =>
                {
                    b.HasOne("projeto.Data.Models.Company", "company")
                        .WithMany("services")
                        .HasForeignKey("companyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("company");
                });

            modelBuilder.Entity("projeto.Data.Models.Task", b =>
                {
                    b.HasOne("projeto.Data.Models.Client", "client")
                        .WithMany("tasks")
                        .HasForeignKey("clientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projeto.Data.Models.Plan", "plan")
                        .WithMany("tasks")
                        .HasForeignKey("planID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("projeto.Data.Models.Service", "service")
                        .WithMany("tasks")
                        .HasForeignKey("serviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projeto.Data.Models.User", "user")
                        .WithMany("tasks")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("projeto.Data.Models.Vehicle", "vehicle")
                        .WithMany()
                        .HasForeignKey("vehicleID");

                    b.Navigation("client");

                    b.Navigation("plan");

                    b.Navigation("service");

                    b.Navigation("user");

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("projeto.Data.Models.User", b =>
                {
                    b.HasOne("projeto.Data.Models.Company", "company")
                        .WithMany("users")
                        .HasForeignKey("companyID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("company");
                });

            modelBuilder.Entity("projeto.Data.Models.Vehicle", b =>
                {
                    b.HasOne("projeto.Data.Models.User", "owner")
                        .WithMany("vehicles")
                        .HasForeignKey("ownerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("owner");
                });

            modelBuilder.Entity("projeto.Data.Models.AssistanceRequest", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("projeto.Data.Models.Client", b =>
                {
                    b.Navigation("tasks");
                });

            modelBuilder.Entity("projeto.Data.Models.Company", b =>
                {
                    b.Navigation("services");

                    b.Navigation("users");
                });

            modelBuilder.Entity("projeto.Data.Models.LocationNode", b =>
                {
                    b.Navigation("LocationNodeTasks");
                });

            modelBuilder.Entity("projeto.Data.Models.Plan", b =>
                {
                    b.Navigation("tasks");
                });

            modelBuilder.Entity("projeto.Data.Models.Service", b =>
                {
                    b.Navigation("tasks");
                });

            modelBuilder.Entity("projeto.Data.Models.Task", b =>
                {
                    b.Navigation("LocationNodeTasks");
                });

            modelBuilder.Entity("projeto.Data.Models.User", b =>
                {
                    b.Navigation("managedAlerts");

                    b.Navigation("plans");

                    b.Navigation("tasks");

                    b.Navigation("vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
